# See:
# - https://github.com/nix-community/nix-github-actions/blob/master/.github/workflows/cachix-install-nix-action.yml
# - https://github.com/DeterminateSystems/nix-github-actions/blob/main/.github/workflows/nix.yml
name: Build git-monitor (Nix)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v30

    - name: Build git-monitor
      run: nix build .#git-monitor
